### ISSUE TITLE
Practicas de HILOS

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipo-buscadores-de-datos#1]
[PRACTICAS SOBRE LOS HILOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipo-buscadores-de-datos/files/15135555/PRACTICAS.SOBRE.LOS.HILOS.pdf)

* Roldan Uriel Arcadio Ávila
* Pedro Garcia Garcia
* Ariadna Monserrat López Aparicio

**Comment by Daniel-Velasco-Lopez** [comment]
En base a la rúbriica, han obtenido el 20% de 20%, cumplen con todos los requerimientos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
